version: '3'

services:
  adonis-mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
    networks:
      - default
  adonis-api:
    container_name: "${APP_NAME}-api"
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - adonis-mysql
    networks:
      - default

networks:
  default:
    driver: bridge